
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86-unknown-bare_metal.json"

[target.x86-unknown-bare_metal]
rustflags = [
    "-C", "opt-level=s",        # Эквивалент GCC -Os
    "-C", "debuginfo=0",        # Убирает отладочную информацию
    "-C", "relocation-model=static",  # Для freestanding
    "--emit=obj"                # Генерация объектного файла
]