
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86-unknown-bare_metal.json"

[target.x86-unknown-bare_metal]
rustflags = [
    "-C", "opt-level=s",
    "-C", "debuginfo=0",
    "-C", "relocation-model=static",
    "--emit=obj"
]